from __future__ import annotations

from copy import deepcopy


GROUPS = {
    "A": ["Mexico", "South Africa", "South Korea", "Czechia"],
    "B": ["Switzerland", "Canada", "Bosnia and Herzegovina", "Qatar"],
    "C": ["Brazil", "Morocco", "Scotland", "Haiti"],
    "D": ["United States", "Australia", "Paraguay", "Türkiye"],
    "E": ["Germany", "Côte d'Ivoire", "Ecuador", "Curaçao"],
    "F": ["Netherlands", "Japan", "Sweden", "Tunisia"],
    "G": ["Egypt", "Iran", "Belgium", "New Zealand"],
    "H": ["Spain", "Uruguay", "Cabo Verde", "Saudi Arabia"],
    "I": ["France", "Norway", "Senegal", "Iraq"],
    "J": ["Argentina", "Austria", "Algeria", "Jordan"],
    "K": ["Colombia", "Portugal", "DR Congo", "Uzbekistan"],
    "L": ["England", "Ghana", "Croatia", "Panama"],
}

SEED_STANDINGS = {
    "A": [
        {"team": "Mexico", "played": 3, "won": 3, "drawn": 0, "lost": 0, "gf": 6, "ga": 0, "gd": 6, "pts": 9, "status": "advanced"},
        {"team": "South Africa", "played": 3, "won": 1, "drawn": 1, "lost": 1, "gf": 2, "ga": 3, "gd": -1, "pts": 4, "status": "advanced"},
        {"team": "South Korea", "played": 3, "won": 1, "drawn": 0, "lost": 2, "gf": 2, "ga": 3, "gd": -1, "pts": 3, "status": "third"},
        {"team": "Czechia", "played": 3, "won": 0, "drawn": 1, "lost": 2, "gf": 2, "ga": 6, "gd": -4, "pts": 1, "status": "eliminated"},
    ],
    "B": [
        {"team": "Switzerland", "played": 3, "won": 2, "drawn": 1, "lost": 0, "gf": 7, "ga": 3, "gd": 4, "pts": 7, "status": "advanced"},
        {"team": "Canada", "played": 3, "won": 1, "drawn": 1, "lost": 1, "gf": 8, "ga": 3, "gd": 5, "pts": 4, "status": "advanced"},
        {"team": "Bosnia and Herzegovina", "played": 3, "won": 1, "drawn": 1, "lost": 1, "gf": 5, "ga": 6, "gd": -1, "pts": 4, "status": "third"},
        {"team": "Qatar", "played": 3, "won": 0, "drawn": 1, "lost": 2, "gf": 2, "ga": 10, "gd": -8, "pts": 1, "status": "eliminated"},
    ],
    "C": [
        {"team": "Brazil", "played": 3, "won": 2, "drawn": 1, "lost": 0, "gf": 7, "ga": 1, "gd": 6, "pts": 7, "status": "advanced"},
        {"team": "Morocco", "played": 3, "won": 2, "drawn": 1, "lost": 0, "gf": 6, "ga": 3, "gd": 3, "pts": 7, "status": "advanced"},
        {"team": "Scotland", "played": 3, "won": 1, "drawn": 0, "lost": 2, "gf": 1, "ga": 4, "gd": -3, "pts": 3, "status": "third"},
        {"team": "Haiti", "played": 3, "won": 0, "drawn": 0, "lost": 3, "gf": 2, "ga": 8, "gd": -6, "pts": 0, "status": "eliminated"},
    ],
    "D": [
        {"team": "United States", "played": 2, "won": 2, "drawn": 0, "lost": 0, "gf": 6, "ga": 1, "gd": 5, "pts": 6, "status": "advanced"},
        {"team": "Australia", "played": 2, "won": 1, "drawn": 0, "lost": 1, "gf": 2, "ga": 2, "gd": 0, "pts": 3, "status": "contending"},
        {"team": "Paraguay", "played": 2, "won": 1, "drawn": 0, "lost": 1, "gf": 2, "ga": 4, "gd": -2, "pts": 3, "status": "third"},
        {"team": "Türkiye", "played": 2, "won": 0, "drawn": 0, "lost": 2, "gf": 0, "ga": 3, "gd": -3, "pts": 0, "status": "eliminated"},
    ],
    "E": [
        {"team": "Germany", "played": 2, "won": 2, "drawn": 0, "lost": 0, "gf": 9, "ga": 2, "gd": 7, "pts": 6, "status": "advanced"},
        {"team": "Côte d'Ivoire", "played": 2, "won": 1, "drawn": 0, "lost": 1, "gf": 2, "ga": 2, "gd": 0, "pts": 3, "status": "contending"},
        {"team": "Ecuador", "played": 2, "won": 0, "drawn": 1, "lost": 1, "gf": 0, "ga": 1, "gd": -1, "pts": 1, "status": "third"},
        {"team": "Curaçao", "played": 2, "won": 0, "drawn": 1, "lost": 1, "gf": 1, "ga": 7, "gd": -6, "pts": 1, "status": "contending"},
    ],
    "F": [
        {"team": "Netherlands", "played": 2, "won": 1, "drawn": 1, "lost": 0, "gf": 7, "ga": 3, "gd": 4, "pts": 4, "status": "contending"},
        {"team": "Japan", "played": 2, "won": 1, "drawn": 1, "lost": 0, "gf": 6, "ga": 2, "gd": 4, "pts": 4, "status": "contending"},
        {"team": "Sweden", "played": 2, "won": 1, "drawn": 0, "lost": 1, "gf": 6, "ga": 6, "gd": 0, "pts": 3, "status": "third"},
        {"team": "Tunisia", "played": 2, "won": 0, "drawn": 0, "lost": 2, "gf": 1, "ga": 9, "gd": -8, "pts": 0, "status": "eliminated"},
    ],
    "G": [
        {"team": "Egypt", "played": 2, "won": 1, "drawn": 1, "lost": 0, "gf": 4, "ga": 2, "gd": 2, "pts": 4, "status": "contending"},
        {"team": "Iran", "played": 2, "won": 0, "drawn": 2, "lost": 0, "gf": 2, "ga": 2, "gd": 0, "pts": 2, "status": "contending"},
        {"team": "Belgium", "played": 2, "won": 0, "drawn": 2, "lost": 0, "gf": 1, "ga": 1, "gd": 0, "pts": 2, "status": "third"},
        {"team": "New Zealand", "played": 2, "won": 0, "drawn": 1, "lost": 1, "gf": 3, "ga": 5, "gd": -2, "pts": 1, "status": "contending"},
    ],
    "H": [
        {"team": "Spain", "played": 2, "won": 1, "drawn": 1, "lost": 0, "gf": 4, "ga": 0, "gd": 4, "pts": 4, "status": "contending"},
        {"team": "Uruguay", "played": 2, "won": 0, "drawn": 2, "lost": 0, "gf": 3, "ga": 3, "gd": 0, "pts": 2, "status": "contending"},
        {"team": "Cabo Verde", "played": 2, "won": 0, "drawn": 2, "lost": 0, "gf": 2, "ga": 2, "gd": 0, "pts": 2, "status": "third"},
        {"team": "Saudi Arabia", "played": 2, "won": 0, "drawn": 1, "lost": 1, "gf": 1, "ga": 5, "gd": -4, "pts": 1, "status": "contending"},
    ],
    "I": [
        {"team": "France", "played": 2, "won": 2, "drawn": 0, "lost": 0, "gf": 6, "ga": 1, "gd": 5, "pts": 6, "status": "advanced"},
        {"team": "Norway", "played": 2, "won": 2, "drawn": 0, "lost": 0, "gf": 7, "ga": 3, "gd": 4, "pts": 6, "status": "advanced"},
        {"team": "Senegal", "played": 2, "won": 0, "drawn": 0, "lost": 2, "gf": 3, "ga": 6, "gd": -3, "pts": 0, "status": "third"},
        {"team": "Iraq", "played": 2, "won": 0, "drawn": 0, "lost": 2, "gf": 1, "ga": 7, "gd": -6, "pts": 0, "status": "contending"},
    ],
    "J": [
        {"team": "Argentina", "played": 2, "won": 2, "drawn": 0, "lost": 0, "gf": 5, "ga": 0, "gd": 5, "pts": 6, "status": "advanced"},
        {"team": "Austria", "played": 2, "won": 1, "drawn": 0, "lost": 1, "gf": 3, "ga": 3, "gd": 0, "pts": 3, "status": "contending"},
        {"team": "Algeria", "played": 2, "won": 1, "drawn": 0, "lost": 1, "gf": 2, "ga": 4, "gd": -2, "pts": 3, "status": "third"},
        {"team": "Jordan", "played": 2, "won": 0, "drawn": 0, "lost": 2, "gf": 2, "ga": 5, "gd": -3, "pts": 0, "status": "eliminated"},
    ],
    "K": [
        {"team": "Colombia", "played": 2, "won": 2, "drawn": 0, "lost": 0, "gf": 4, "ga": 1, "gd": 3, "pts": 6, "status": "advanced"},
        {"team": "Portugal", "played": 2, "won": 1, "drawn": 1, "lost": 0, "gf": 6, "ga": 1, "gd": 5, "pts": 4, "status": "contending"},
        {"team": "DR Congo", "played": 2, "won": 0, "drawn": 1, "lost": 1, "gf": 1, "ga": 2, "gd": -1, "pts": 1, "status": "third"},
        {"team": "Uzbekistan", "played": 2, "won": 0, "drawn": 0, "lost": 2, "gf": 1, "ga": 8, "gd": -7, "pts": 0, "status": "contending"},
    ],
    "L": [
        {"team": "England", "played": 2, "won": 1, "drawn": 1, "lost": 0, "gf": 4, "ga": 2, "gd": 2, "pts": 4, "status": "contending"},
        {"team": "Ghana", "played": 2, "won": 1, "drawn": 1, "lost": 0, "gf": 1, "ga": 0, "gd": 1, "pts": 4, "status": "contending"},
        {"team": "Croatia", "played": 2, "won": 1, "drawn": 0, "lost": 1, "gf": 3, "ga": 4, "gd": -1, "pts": 3, "status": "third"},
        {"team": "Panama", "played": 2, "won": 0, "drawn": 0, "lost": 2, "gf": 0, "ga": 2, "gd": -2, "pts": 0, "status": "eliminated"},
    ],
}

MATCHES = [
    ("A", "2026-06-11", "Mexico", "South Africa", 2, 0, "FT"),
    ("A", "2026-06-11", "South Korea", "Czechia", 2, 1, "FT"),
    ("A", "2026-06-18", "Czechia", "South Africa", 1, 1, "FT"),
    ("A", "2026-06-18", "Mexico", "South Korea", 1, 0, "FT"),
    ("A", "2026-06-24", "South Africa", "South Korea", 1, 0, "FT"),
    ("A", "2026-06-24", "Mexico", "Czechia", 3, 0, "FT"),
    ("B", "2026-06-12", "Canada", "Bosnia and Herzegovina", 1, 1, "FT"),
    ("B", "2026-06-13", "Qatar", "Switzerland", 1, 1, "FT"),
    ("B", "2026-06-18", "Switzerland", "Bosnia and Herzegovina", 4, 1, "FT"),
    ("B", "2026-06-18", "Canada", "Qatar", 6, 0, "FT"),
    ("B", "2026-06-24", "Switzerland", "Canada", 2, 1, "FT"),
    ("B", "2026-06-24", "Bosnia and Herzegovina", "Qatar", 3, 1, "FT"),
    ("C", "2026-06-13", "Brazil", "Morocco", 1, 1, "FT"),
    ("C", "2026-06-13", "Scotland", "Haiti", 1, 0, "FT"),
    ("C", "2026-06-19", "Morocco", "Scotland", 1, 0, "FT"),
    ("C", "2026-06-19", "Brazil", "Haiti", 3, 0, "FT"),
    ("C", "2026-06-24", "Morocco", "Haiti", 4, 2, "FT"),
    ("C", "2026-06-24", "Brazil", "Scotland", 3, 0, "FT"),
    ("D", "2026-06-12", "United States", "Paraguay", 4, 1, "FT"),
    ("D", "2026-06-13", "Australia", "Türkiye", 2, 0, "FT"),
    ("D", "2026-06-19", "United States", "Australia", 2, 0, "FT"),
    ("D", "2026-06-19", "Paraguay", "Türkiye", 1, 0, "FT"),
    ("D", "2026-06-25", "Türkiye", "United States", None, None, "Scheduled"),
    ("D", "2026-06-25", "Paraguay", "Australia", None, None, "Scheduled"),
    ("E", "2026-06-14", "Germany", "Curaçao", 7, 1, "FT"),
    ("E", "2026-06-14", "Côte d'Ivoire", "Ecuador", 1, 0, "FT"),
    ("E", "2026-06-20", "Germany", "Côte d'Ivoire", 2, 1, "FT"),
    ("E", "2026-06-20", "Ecuador", "Curaçao", 0, 0, "FT"),
    ("E", "2026-06-25", "Curaçao", "Côte d'Ivoire", None, None, "Live"),
    ("E", "2026-06-25", "Ecuador", "Germany", None, None, "Live"),
    ("F", "2026-06-14", "Netherlands", "Japan", 2, 2, "FT"),
    ("F", "2026-06-14", "Sweden", "Tunisia", 5, 1, "FT"),
    ("F", "2026-06-20", "Netherlands", "Sweden", 5, 1, "FT"),
    ("F", "2026-06-21", "Tunisia", "Japan", 0, 4, "FT"),
    ("F", "2026-06-25", "Tunisia", "Netherlands", None, None, "Scheduled"),
    ("F", "2026-06-25", "Japan", "Sweden", None, None, "Scheduled"),
    ("G", "2026-06-15", "Belgium", "Egypt", 1, 1, "FT"),
    ("G", "2026-06-15", "Iran", "New Zealand", 2, 2, "FT"),
    ("G", "2026-06-21", "Belgium", "Iran", 0, 0, "FT"),
    ("G", "2026-06-21", "New Zealand", "Egypt", 1, 3, "FT"),
    ("G", "2026-06-26", "New Zealand", "Belgium", None, None, "Scheduled"),
    ("G", "2026-06-26", "Egypt", "Iran", None, None, "Scheduled"),
    ("H", "2026-06-15", "Spain", "Cabo Verde", 0, 0, "FT"),
    ("H", "2026-06-15", "Saudi Arabia", "Uruguay", 1, 1, "FT"),
    ("H", "2026-06-21", "Spain", "Saudi Arabia", 4, 0, "FT"),
    ("H", "2026-06-21", "Uruguay", "Cabo Verde", 2, 2, "FT"),
    ("H", "2026-06-26", "Cabo Verde", "Saudi Arabia", None, None, "Scheduled"),
    ("H", "2026-06-26", "Uruguay", "Spain", None, None, "Scheduled"),
    ("I", "2026-06-16", "France", "Senegal", 3, 1, "FT"),
    ("I", "2026-06-16", "Norway", "Iraq", 4, 1, "FT"),
    ("I", "2026-06-22", "France", "Iraq", 3, 0, "FT"),
    ("I", "2026-06-22", "Norway", "Senegal", 3, 2, "FT"),
    ("I", "2026-06-26", "Norway", "France", None, None, "Scheduled"),
    ("I", "2026-06-26", "Senegal", "Iraq", None, None, "Scheduled"),
    ("J", "2026-06-16", "Argentina", "Algeria", 3, 0, "FT"),
    ("J", "2026-06-17", "Austria", "Jordan", 3, 1, "FT"),
    ("J", "2026-06-22", "Argentina", "Austria", 2, 0, "FT"),
    ("J", "2026-06-22", "Algeria", "Jordan", 2, 1, "FT"),
    ("J", "2026-06-27", "Algeria", "Austria", None, None, "Scheduled"),
    ("J", "2026-06-27", "Jordan", "Argentina", None, None, "Scheduled"),
    ("K", "2026-06-17", "Portugal", "DR Congo", 1, 1, "FT"),
    ("K", "2026-06-17", "Colombia", "Uzbekistan", 3, 1, "FT"),
    ("K", "2026-06-23", "Portugal", "Uzbekistan", 5, 0, "FT"),
    ("K", "2026-06-23", "Colombia", "DR Congo", 1, 0, "FT"),
    ("K", "2026-06-27", "Colombia", "Portugal", None, None, "Scheduled"),
    ("K", "2026-06-27", "DR Congo", "Uzbekistan", None, None, "Scheduled"),
    ("L", "2026-06-17", "England", "Croatia", 4, 2, "FT"),
    ("L", "2026-06-17", "Ghana", "Panama", 1, 0, "FT"),
    ("L", "2026-06-23", "England", "Ghana", 0, 0, "FT"),
    ("L", "2026-06-23", "Croatia", "Panama", 1, 0, "FT"),
    ("L", "2026-06-27", "Panama", "England", None, None, "Scheduled"),
    ("L", "2026-06-27", "Croatia", "Ghana", None, None, "Scheduled"),
]

KNOCKOUT = [
    {"round": "Round of 32", "date": "2026-06-28", "slot": "R32-1", "home": "Winner Group A", "away": "3rd Group C/E/F/H/I"},
    {"round": "Round of 32", "date": "2026-06-28", "slot": "R32-2", "home": "Runner-up Group B", "away": "Runner-up Group A"},
    {"round": "Round of 32", "date": "2026-06-29", "slot": "R32-3", "home": "Winner Group C", "away": "Runner-up Group F"},
    {"round": "Round of 32", "date": "2026-06-29", "slot": "R32-4", "home": "Winner Group E", "away": "3rd Group A/B/C/D/F"},
    {"round": "Round of 32", "date": "2026-06-30", "slot": "R32-5", "home": "Winner Group D", "away": "3rd Group B/E/F/I/J"},
    {"round": "Round of 32", "date": "2026-06-30", "slot": "R32-6", "home": "Runner-up Group E", "away": "Runner-up Group I"},
    {"round": "Round of 32", "date": "2026-07-01", "slot": "R32-7", "home": "Winner Group F", "away": "Runner-up Group C"},
    {"round": "Round of 32", "date": "2026-07-01", "slot": "R32-8", "home": "Winner Group I", "away": "3rd Group C/D/F/G/H"},
    {"round": "Round of 32", "date": "2026-07-01", "slot": "R32-9", "home": "Winner Group B", "away": "3rd Group E/F/G/I/J"},
    {"round": "Round of 32", "date": "2026-07-02", "slot": "R32-10", "home": "Runner-up Group D", "away": "Runner-up Group G"},
    {"round": "Round of 32", "date": "2026-07-02", "slot": "R32-11", "home": "Winner Group G", "away": "3rd Group A/B/C/H/I"},
    {"round": "Round of 32", "date": "2026-07-02", "slot": "R32-12", "home": "Winner Group H", "away": "3rd Group A/B/C/D/G"},
    {"round": "Round of 32", "date": "2026-07-03", "slot": "R32-13", "home": "Winner Group J", "away": "3rd Group D/E/F/G/I"},
    {"round": "Round of 32", "date": "2026-07-03", "slot": "R32-14", "home": "Winner Group K", "away": "3rd Group A/B/D/I/L"},
    {"round": "Round of 32", "date": "2026-07-03", "slot": "R32-15", "home": "Winner Group L", "away": "3rd Group E/H/I/J/K"},
    {"round": "Round of 32", "date": "2026-07-03", "slot": "R32-16", "home": "Runner-up Group L", "away": "Runner-up Group K"},
    {"round": "Round of 16", "date": "2026-07-04", "slot": "R16-1", "home": "Winner R32-1", "away": "Winner R32-2"},
    {"round": "Round of 16", "date": "2026-07-04", "slot": "R16-2", "home": "Winner R32-3", "away": "Winner R32-4"},
    {"round": "Round of 16", "date": "2026-07-05", "slot": "R16-3", "home": "Winner R32-5", "away": "Winner R32-6"},
    {"round": "Round of 16", "date": "2026-07-05", "slot": "R16-4", "home": "Winner R32-7", "away": "Winner R32-8"},
    {"round": "Round of 16", "date": "2026-07-06", "slot": "R16-5", "home": "Winner R32-9", "away": "Winner R32-10"},
    {"round": "Round of 16", "date": "2026-07-06", "slot": "R16-6", "home": "Winner R32-11", "away": "Winner R32-12"},
    {"round": "Round of 16", "date": "2026-07-07", "slot": "R16-7", "home": "Winner R32-13", "away": "Winner R32-14"},
    {"round": "Round of 16", "date": "2026-07-07", "slot": "R16-8", "home": "Winner R32-15", "away": "Winner R32-16"},
    {"round": "Quarterfinal", "date": "2026-07-09", "slot": "QF-1", "home": "Winner R16-1", "away": "Winner R16-2"},
    {"round": "Quarterfinal", "date": "2026-07-10", "slot": "QF-2", "home": "Winner R16-3", "away": "Winner R16-4"},
    {"round": "Quarterfinal", "date": "2026-07-11", "slot": "QF-3", "home": "Winner R16-5", "away": "Winner R16-6"},
    {"round": "Quarterfinal", "date": "2026-07-11", "slot": "QF-4", "home": "Winner R16-7", "away": "Winner R16-8"},
    {"round": "Semifinal", "date": "2026-07-14", "slot": "SF-1", "home": "Winner QF-1", "away": "Winner QF-2"},
    {"round": "Semifinal", "date": "2026-07-15", "slot": "SF-2", "home": "Winner QF-3", "away": "Winner QF-4"},
    {"round": "Third Place", "date": "2026-07-18", "slot": "3P", "home": "Loser SF-1", "away": "Loser SF-2"},
    {"round": "Final", "date": "2026-07-19", "slot": "Final", "home": "Winner SF-1", "away": "Winner SF-2"},
]

PLAYER_STATS = [
    {"player": "Lionel Messi", "team": "Argentina", "goals": 2, "assists": 0, "yellowCards": 0, "redCards": 0},
    {"player": "Erling Haaland", "team": "Norway", "goals": 2, "assists": 0, "yellowCards": 0, "redCards": 0},
    {"player": "Nicolas Pépé", "team": "Côte d'Ivoire", "goals": 2, "assists": 0, "yellowCards": 0, "redCards": 0},
    {"player": "Vinícius Júnior", "team": "Brazil", "goals": 2, "assists": 0, "yellowCards": 0, "redCards": 0},
    {"player": "Cody Gakpo", "team": "Netherlands", "goals": 2, "assists": 0, "yellowCards": 0, "redCards": 0},
    {"player": "Brian Brobbey", "team": "Netherlands", "goals": 2, "assists": 0, "yellowCards": 0, "redCards": 0},
    {"player": "Kylian Mbappé", "team": "France", "goals": 2, "assists": 0, "yellowCards": 0, "redCards": 0},
    {"player": "Cristiano Ronaldo", "team": "Portugal", "goals": 1, "assists": 0, "yellowCards": 0, "redCards": 0},
    {"player": "Luis Romo", "team": "Mexico", "goals": 1, "assists": 0, "yellowCards": 0, "redCards": 0},
    {"player": "Johan Manzambi", "team": "Switzerland", "goals": 1, "assists": 0, "yellowCards": 0, "redCards": 0},
    {"player": "Rubén Vargas", "team": "Switzerland", "goals": 1, "assists": 0, "yellowCards": 0, "redCards": 0},
    {"player": "Amad Diallo", "team": "Côte d'Ivoire", "goals": 1, "assists": 0, "yellowCards": 0, "redCards": 0},
    {"player": "Leroy Sané", "team": "Germany", "goals": 1, "assists": 0, "yellowCards": 0, "redCards": 0},
    {"player": "Nilson Angulo", "team": "Ecuador", "goals": 1, "assists": 0, "yellowCards": 0, "redCards": 0},
]


def seed_payload():
    matches = []
    for idx, (group, date, home, away, home_score, away_score, status) in enumerate(MATCHES, start=1):
        matches.append(
            {
                "id": f"M{idx:03d}",
                "group": group,
                "date": date,
                "home": home,
                "away": away,
                "homeScore": home_score,
                "awayScore": away_score,
                "status": status,
            }
        )
    return {
        "lastUpdated": "2026-06-25T15:03:00-07:00",
        "sourceNote": "Seeded from verified public standings; use Refresh for live attempts or edit scores locally.",
        "groups": deepcopy(SEED_STANDINGS),
        "matches": matches,
        "knockout": deepcopy(KNOCKOUT),
        "playerStats": deepcopy(PLAYER_STATS),
        "playerStatsNote": "Player stats include every player currently available in the local stats feed. Goals are partially populated from public match reports; assists and cards need an official feed or manual entry.",
    }
